var homeSlider = require('./home/homeSlider.js')
// var headerEntrance = require('./home/headerEntrance.js')
var revealText = require('./home/revealText.js')
var stickyMenu = require('./home/stickyMenu.js')
// var menuResponsive = require('./global/menuResponsive.js')

homeSlider()
// menuResponsive()
revealText()
stickyMenu()
// headerEntrance()